language: php

cache:
  apt: true
  directories:
    - vendor
    - bin

matrix:
  include:
    - php: 5.4
      env:
        - DEPENDENCIES='low'
    - php: 5.5
    - php: 5.6
    - php: 7.0

services:
  - elasticsearch

before_script:
  - composer self-update
  - if [[ "$DEPENDENCIES" != "low" ]]; then composer update; fi;
  - if [[ "$DEPENDENCIES" == "low" ]]; then composer update --prefer-lowest; fi;

script: bin/phpunit
