language: php

cache:
  apt: true
  directories:
    - vendor
    - bin

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - elasticsearch

before_script:
  - composer self-update
  - composer update

script: bin/phpunit
