language: php

cache:
  apt: true
  directories:
    - vendor
    - bin

matrix:
  include:
    - php: 5.6
      env:
        - DEPENDENCIES='low'
    - php: 7.0
    - php: 7.1

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.1.deb
  - sudo dpkg -i --force-confnew elasticsearch-5.3.1.deb
  - sudo service elasticsearch restart

before_script:
  - sleep 10 # for elasticsearch (from travis documentation)
  - composer self-update
  - if [[ "$DEPENDENCIES" != "low" ]]; then composer update; fi;
  - if [[ "$DEPENDENCIES" == "low" ]]; then composer update --prefer-lowest; fi;

script: bin/phpunit
